### ISSUE TITLE
Reconnect on Fatal Error

### ISSUE THREAD

**Issue by Fabbok1x** [nevill/zongji#125]
Hey,
just wondering if it was possible to recover from a fatal error such as Packet was received in wrong sequence / Same slave already existing?
Currently it seems to stop as a whole once a fatal error has been thrown. 
Anything to attempt a reconnection would be greatly appreciated.

Regards

**Comment by vasyas** [comment]
Need this very bad. Any known possible workarounds?

If not, any clues where to start to fix it?

P.S. Getting this sometimes on MySQL 8 on Amazon RDS:
```
Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/home/server/server/shared-server/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/home/server/server/shared-server/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at Connection.query (/home/server/server/shared-server/node_modules/mysql/lib/Connection.js:201:25)
```
