### ISSUE TITLE
UnhandledPromiseRejectionWarning: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by stu31** [nevill/zongji#130]
Using version 0.4.7.  Was this issue resolved?

(node:1) UnhandledPromiseRejectionWarning: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at Buffer.readUInt8 (internal/buffer.js:213:5)
    at readRow (/app/src/node_modules/zongji/lib/rows_event.js:106:48)
    at WriteRows.RowsEvent._fetchOneRow (/app/src/node_modules/zongji/lib/rows_event.js:93:10)
    at WriteRows.RowsEvent (/app/src/node_modules/zongji/lib/rows_event.js:62:27)
    at new WriteRows (/app/src/node_modules/zongji/lib/rows_event.js:121:13)
    at BinlogHeader.parse (/app/src/node_modules/zongji/lib/packet/binlog_header.js:47:23)
    at Protocol._parsePacket (/app/src/node_modules/mysql/lib/protocol/Protocol.js:261:12)
    at Parser.write (/app/src/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/app/src/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/app/src/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at Socket.Readable.read (_stream_readable.js:505:10)
    at flow (_stream_readable.js:974:34)
    at resume_ (_stream_readable.js:955:3)

**Comment by sam26880** [comment]
any reason why this was closed? We're noticing this issues every once in a while.

**Comment by psuhas** [comment]
Seeing the same error... it is definitely repeatable. Not sure how can I help but this a blocking issue for us. Any workaround here? Thank you
