### ISSUE TITLE
Crash when parsing utf8mb3 BLOB columns (MariaDB 10.7) Tag: v0.5.1

### ISSUE THREAD

**Issue by juan-ferrer-toribio** [nevill/zongji#143]
Because MariaDB 10.7 has renamed _utf8_ to _utf8mb3_ (wich is the real econding name, also supported by MySQL), `iconv.decode()` function fails when _utf8mb3_ is passed as encoding (second parameter) when parsing BLOB columns.

```
Error: Encoding not recognized: 'utf8mb3' (searched as: 'utf8mb3')
    at Object.getCodec (iconv-lite/lib/index.js:104:23)
    at Object.getDecoder (iconv-lite/lib/index.js:125:23)
    at Object.decode (iconv-lite/lib/index.js:38:25)
    at Object.readMysqlValue (zongji/lib/common.js:470:23)
    ...
```

**Comment by juan-ferrer-toribio** [comment]
Pull request created #144
