### ISSUE TITLE
ERR_BUFFER_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by sam26880** [nevill/zongji#145]
I sometime get this error

```
**Error: Packets out of order. Got: 247 Expected: 52
err.code: PROTOCOL_PACKETS_OUT_OF_ORDER**
```

any idea what is causing this and how do we go about fixing this?

**Comment by elderapo** [comment]
I am getting similar errors:
```bash
Warning: got packets out of order. Expected 24 but received 0
Warning: got packets out of order. Expected 24 but received 0
Warning: got packets out of order. Expected 8 but received 0
Warning: got packets out of order. Expected 24 but received 0
Warning: got packets out of order. Expected 24 but received 0
Warning: got packets out of order. Expected 24 but received 0
Warning: got packets out of order. Expected 24 but received 0
Warning: got packets out of order. Expected 7 but received 0
Warning: got packets out of order. Expected 24 but received 0
Warning: got packets out of order. Expected 7 but received 0


Error: Packets out of order. Got: 0 Expected: 30
    at Parser._tryReadPacketHeader (/usr/src/app/node_modules/@vlasky/mysql/lib/protocol/Parser.js:640:15)
    at Parser.write (/usr/src/app/node_modules/@vlasky/mysql/lib/protocol/Parser.js:46:29)
    at Protocol.write (/usr/src/app/node_modules/@vlasky/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/@vlasky/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/@vlasky/mysql/lib/Connection.js:529:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}!

Error: Packets out of order. Got: 0 Expected: 13
    at Parser._tryReadPacketHeader (/usr/src/app/node_modules/@vlasky/mysql/lib/protocol/Parser.js:640:15)
    at Parser.write (/usr/src/app/node_modules/@vlasky/mysql/lib/protocol/Parser.js:46:29)
    at Protocol.write (/usr/src/app/node_modules/@vlasky/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/src/app/node_modules/@vlasky/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/@vlasky/mysql/lib/Connection.js:529:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}!
```
