### ISSUE TITLE
RangeError: Trying to access beyond buffer length

### ISSUE THREAD

**Issue by robertpitt** [nevill/zongji#15]
Every now and again I get this parsing error, thought I would send the trace in case you 

```shell
W20150522-13:48:31.186(1)? (STDERR) 
W20150522-13:48:31.187(1)? (STDERR) /home/rpitt/sync/.meteor/local/isopacks/sync_tickets/npm/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:82
W20150522-13:48:31.187(1)? (STDERR)         throw err;
W20150522-13:48:31.187(1)? (STDERR)               ^
W20150522-13:48:31.191(1)? (STDERR) RangeError: Trying to access beyond buffer length
W20150522-13:48:31.191(1)? (STDERR)     at checkOffset (buffer.js:582:11)
W20150522-13:48:31.191(1)? (STDERR)     at Buffer.readInt8 (buffer.js:631:5)
W20150522-13:48:31.191(1)? (STDERR)     at parseNewDecimal (/home/rpitt/sync/.meteor/local/isopacks/sync_tickets/npm/node_modules/zongji/lib/common.js:227:28)
W20150522-13:48:31.191(1)? (STDERR)     at Object.exports.readMysqlValue (/home/rpitt/sync/.meteor/local/isopacks/sync_tickets/npm/node_modules/zongji/lib/common.js:382:16)
W20150522-13:48:31.192(1)? (STDERR)     at readRow (/home/rpitt/sync/.meteor/local/isopacks/sync_tickets/npm/node_modules/zongji/lib/rows_event.js:111:33)
W20150522-13:48:31.192(1)? (STDERR)     at WriteRows.RowsEvent._fetchOneRow (/home/rpitt/sync/.meteor/local/isopacks/sync_tickets/npm/node_modules/zongji/lib/rows_event.js:94:10)
W20150522-13:48:31.192(1)? (STDERR)     at WriteRows.RowsEvent (/home/rpitt/sync/.meteor/local/isopacks/sync_tickets/npm/node_modules/zongji/lib/rows_event.js:63:27)
W20150522-13:48:31.192(1)? (STDERR)     at new WriteRows (/home/rpitt/sync/.meteor/local/isopacks/sync_tickets/npm/node_modules/zongji/lib/rows_event.js:121:13)
W20150522-13:48:31.192(1)? (STDERR)     at BinlogHeader.parse (/home/rpitt/sync/.meteor/local/isopacks/sync_tickets/npm/node_modules/zongji/lib/packet/binlog_header.js:47:23)
W20150522-13:48:31.193(1)? (STDERR)     at Protocol._parsePacket (/home/rpitt/sync/.meteor/local/isopacks/sync_tickets/npm/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:253:12)
```

**Comment by numtel** [comment]
Do you know which column types and/or values it's trying to parse? Also, which version of mysql?

**Comment by robertpitt** [comment]
MySql Version: 5.6.19

Unfortunately, I don't know what column type it was trying to parse, the database I am working with is a support system (Sirportly)..

Im was monitoring around 5 tables (tickets, tags, ticket_updates, contacts, slas) and causing changes from those tables in the Sirportly UI.

Not of said changes caused the issue, leaving it running for a short while would trigger that exception (sometimes) so without better logging and data  traces it's hard for me to reproduce.

**Comment by robertpitt** [comment]
BTW @numtel, this isn't using your live-select or meteor package, this is Zongji directly in meteor.
