### ISSUE TITLE
Cannot read property 'COLUMN_NAME' of undefined

### ISSUE THREAD

**Issue by robertpitt** [nevill/zongji#16]
Hey,

I have a repeatable issue where `tableMap.columnSchemas` is always empty, I have dumped out the TableMap instance just before the error occurs.

The error log:

```shell
/home/rpitt/sync/MySQLSubscription/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'COLUMN_NAME' of undefined
    at TableMap.updateColumnInfo (/home/rpitt/sync/MySQLSubscription/node_modules/zongji/lib/binlog_event.js:165:29)
    at /home/rpitt/sync/MySQLSubscription/node_modules/zongji/index.js:185:19
    at Query._callback (/home/rpitt/sync/MySQLSubscription/node_modules/zongji/index.js:159:5)
    at Query.Sequence.end (/home/rpitt/sync/MySQLSubscription/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/home/rpitt/sync/MySQLSubscription/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/home/rpitt/sync/MySQLSubscription/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/home/rpitt/sync/MySQLSubscription/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/home/rpitt/sync/MySQLSubscription/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/home/rpitt/sync/MySQLSubscription/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/rpitt/sync/MySQLSubscription/node_modules/zongji/node_modules/mysql/lib/Connection.js:82:28)
```

The object:

```js
{ timestamp: 1432656155000,
  nextPosition: 83341787,
  size: 42,
  tableMap: 
   { '15450': 
      { columnSchemas: [],
        parentSchema: 'platform',
        tableName: 'sessions' } },
  tableId: 15450,
  flags: 1,
  schemaName: 'platform',
  tableName: 'sessions',
  columnCount: 5,
  columnTypes: [ 254, 15, 3, 252, 17 ],
  columnsMetadata: 
   [ { max_length: 96 },
     { max_length: 96 },
     undefined,
     { length_size: 2 },
     { decimals: 0 } ] }
```

The schema:

```sql
CREATE TABLE `sessions` (
  `id` char(32) COLLATE utf8_bin NOT NULL,
  `name` varchar(32) COLLATE utf8_bin NOT NULL DEFAULT 'default',
  `account_id` int(11) DEFAULT NULL,
  `data` blob,
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `updated` (`updated`),
  KEY `sess_to_acc` (`account_id`),
  CONSTRAINT `session_to_acc` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
```

Regards.

**Comment by robertpitt** [comment]
Having the same issue occur with the following schema as well:

```sql
CREATE TABLE `credentials` (
  `account_id` int(10) NOT NULL,
  `hash` varchar(255) NOT NULL,
  `type` varchar(45) NOT NULL,
  KEY `cred_aid_hash_type` (`account_id`,`hash`,`type`),
  KEY `fk_credentials_1` (`account_id`),
  CONSTRAINT `fk_credentials_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='This table stores any hash based credentials for an account\n'
```

**Comment by robertpitt** [comment]
Ok so it seems to be because the replication user never had the right privileges on the said tables.
