### ISSUE TITLE
TypeError: Cannot read property 'COLUMN_NAME' of undefined

### ISSUE THREAD

**Issue by saller** [nevill/zongji#17]
The example works without problems on OSX but on Ubuntu I get the following error:

```
/root/livesql/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'COLUMN_NAME' of undefined
    at TableMap.updateColumnInfo (/root/livesql/node_modules/zongji/lib/binlog_event.js:164:29)
    at /root/livesql/node_modules/zongji/index.js:185:19
    at Query._callback (/root/livesql/node_modules/zongji/index.js:159:5)
    at Query.Sequence.end (/root/livesql/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/root/livesql/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/root/livesql/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/root/livesql/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/root/livesql/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/root/livesql/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/livesql/node_modules/zongji/node_modules/mysql/lib/Connection.js:82:28)
```

Here is the MySQL version on Ubuntu.

```
> mysql --version
mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3
```

**Comment by numtel** [comment]
Can you give more information about this? Is it just one query or table that's causing the failure while others are working? If so, what is the query? Can you provide any information about the failing schema?

**Comment by saller** [comment]
There was a problem with the permissions of the tables. The replication user also needs SELECT privileges. It would be great if you could mention this case in the documentation. (I did not have this problem on OSX though.)
