### ISSUE TITLE
Cannot read property 'COLUMN_NAME' of undefined

### ISSUE THREAD

**Issue by chenj28** [nevill/zongji#20]
=== TableMap ===
Date: Thu Jun 25 2015 05:38:05 GMT+0800 (CST)
Next log position: 72907
Event size: 39
Table id: 156
Schema: CCLC_PD
Table: autotask
Columns: 6
Column types: [ 8, 1, 8, 17, 1, 15 ]
undefined
Next position: 72907
15:15                     CCLC_PD.autotask:tablemap
=== UpdateRows ===
Date: Thu Jun 25 2015 05:38:05 GMT+0800 (CST)
Next log position: 72989
Event size: 59
Affected columns: 6
Changed rows: 1
Values:
--
Column: id, Value: 9561 => 9561
Column: type, Value: 73 => 73
Column: recid, Value: 735 => 735
Column: execdate, Value: Thu Jun 25 2015 05:38:04 GMT+0800 (CST) => Thu Jun 25 2015 05:39:05 GMT+0800 (CST)
Column: state, Value: 33 => 2
Column: err, Value: null => null
undefined
Next position: 72989
15:15                     CCLC_PD.autotask:updaterows
{ timestamp: 1435181925000,
  nextPosition: 73661,
  size: 61,
  tableMap: 
   { '156': 
      { columnSchemas: [Object],
        parentSchema: 'CCLC_PD',
        tableName: 'autotask',
        columns: [Object] },
     '160': 
      { columnSchemas: [Object],
        parentSchema: 'CCLC_PD',
        tableName: 'autoinvest_quene',
        columns: [Object] },
     '186': 
      { columnSchemas: [Object],
        parentSchema: 'CCLC_PD',
        tableName: 'withdraw' } },
  tableId: 186,
  flags: 1,
  schemaName: 'CCLC_PD',
  tableName: 'withdraw',
  columnCount: 15,
  columnTypes: [ 8, 8, 8, 246, 1, 15, 15, 17, 17, 246, 1, 3, 17, 246, 15 ],
  columnsMetadata: 
   [ undefined,
     undefined,
     undefined,
     { precision: 10, decimals: 2 },
     undefined,
     { max_length: 900 },
     { max_length: 900 },
     { decimals: 0 },
     { decimals: 0 },
     { precision: 6, decimals: 2 },
     undefined,
     undefined,
     { decimals: 0 },
     { precision: 10, decimals: 2 },
     { max_length: 600 } ] }
/data/cclc/cclc-node2/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'COLUMN_NAME' of undefined
    at TableMap.updateColumnInfo (/data/cclc/cclc-node2/node_modules/zongji/lib/binlog_event.js:166:29)
    at /data/cclc/cclc-node2/node_modules/zongji/index.js:185:19
    at Query._callback (/data/cclc/cclc-node2/node_modules/zongji/index.js:159:5)
    at Query.Sequence.end (/data/cclc/cclc-node2/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/data/cclc/cclc-node2/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/data/cclc/cclc-node2/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/data/cclc/cclc-node2/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/data/cclc/cclc-node2/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/data/cclc/cclc-node2/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/data/cclc/cclc-node2/node_modules/zongji/node_modules/mysql/lib/Connection.js:82:28)

**Comment by DoubleSpout** [comment]
https://github.com/nevill/zongji/pull/21
I have the same problem, I have fixed the bug:
see that : https://github.com/nevill/zongji/pull/21

**Comment by nevill** [comment]
@chenj28 seems @DoubleSpout have the same bug as yours according to his screenshot, could you please confirm that? Is it caused by changing the table name?

**Comment by jmealo** [comment]
I'm now encountering this error (and I previously had not). I'm on Ubuntu 14.04 (64-bit) using mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.3.

Unfortunately, I'm unsure which version of MySQL I was using before it stopped working.
