### ISSUE TITLE
Cannot read property 'COLUMN_NAME' of undefined

### ISSUE THREAD

**Issue by DoubleSpout** [nevill/zongji#22]
https://github.com/nevill/zongji/pull/21

**Comment by rodrigogs** [comment]
I "fixed" that in my fork: https://github.com/rodrigogs/zongji

It happens when there's information in the binlog from a table that already have been dropped or altered.

My "solution" was to simply emit the error and ignore the record.

**Comment by Bkhxq** [comment]
same problem, anyone can tell me how to fix it:

D:\Code\api\node_modules\zongji\node_modules\mysql\lib\protocol\Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError: Cannot read property 'COLUMN_NAME' of undefined
    at TableMap.updateColumnInfo (D:\Code\api\node_modules\zongji\lib\binlog_event.js:195:30)
    at D:\Code\api\node_modules\zongji\index.js:259:19
    at Query.<anonymous> (D:\Code\api\node_modules\zongji\index.js:150:5)
    at Query.<anonymous> (D:\Code\api\node_modules\zongji\node_modules\mysql\lib\Connection.js:525:10)
    at Query._callback (D:\Code\api\node_modules\zongji\node_modules\mysql\lib\Connection.js:491:16)
    at Query.Sequence.end (D:\Code\api\node_modules\zongji\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (D:\Code\api\node_modules\zongji\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)
    at Query.EofPacket (D:\Code\api\node_modules\zongji\node_modules\mysql\lib\protocol\sequences\Query.js:123:8)
    at Protocol._parsePacket (D:\Code\api\node_modules\zongji\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\Code\api\node_modules\zongji\node_modules\mysql\lib\protocol\Parser.js:433:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by taieb-tk** [comment]
Any solution to this problem @Bkhxq / @rodrigogs ?
