### ISSUE TITLE
leaking errors

### ISSUE THREAD

**Issue by oskude** [nevill/zongji#28]
am i doing something wrong?
```javascript
var Zongji = require("zongji");

try {
	var zongi = new Zongji();
} catch (e) {
	console.log(e);
	console.log("this should be last line");
}
```

```
❱ node hmm1.js 
[TypeError: Cannot read property 'host' of undefined]
this should be last line
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1053:14)
    --------------------
    at Protocol._enqueue (/data/projects/nodejs/hmm/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/data/projects/nodejs/hmm/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/data/projects/nodejs/hmm/node_modules/mysql/lib/Connection.js:109:18)
    at new ZongJi (/data/projects/nodejs/hmm/node_modules/zongji/index.js:15:23)
    at Object.<anonymous> (/data/projects/nodejs/hmm/hmm1.js:4:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by numtel** [comment]
Your ZongJi constructor needs to include an object containing the MySql connection settings.

https://github.com/nevill/zongji/blob/master/README.md#zongji-class

**Comment by oskude** [comment]
is the same with wrong data (from user), thats what i would like to catch

```javascript
var Zongji = require("zongji");

try {
	var zongi = new Zongji({
		host: 'wronghost',
		user: "wronguser",
		password: "wrongpass"
	});
} catch (e) {
	console.log(e);
	console.log("this should be last line");
}
```

```
❱ node hmm2.js 
/data/projects/nodejs/hmm/node_modules/zongji/index.js:102
      throw err;
      ^

Error: getaddrinfo ENOTFOUND wronghost wronghost:3306
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
    --------------------
    at Protocol._enqueue (/data/projects/nodejs/hmm/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/data/projects/nodejs/hmm/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/data/projects/nodejs/hmm/node_modules/mysql/lib/Connection.js:109:18)
    at new ZongJi (/data/projects/nodejs/hmm/node_modules/zongji/index.js:15:23)
    at Object.<anonymous> (/data/projects/nodejs/hmm/hmm2.js:4:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by numtel** [comment]
Ah that issue. The code has been written to fix this but hasn't been released yet.

https://github.com/nevill/zongji/commit/523950deeca571cfc84c136c8ec972c4ef415f1a

I'll see if I can get this ready to go out in the next week.

**Comment by jmealo** [comment]
@oskude My fork should work: https://github.com/jmealo/zongji
