### ISSUE TITLE
Index out of range error on running tests

### ISSUE THREAD

**Issue by criticalboot** [nevill/zongji#55]
tests are failing with index out of range error.
>
>=== TableMap ===
Date: Wed Dec 28 2016 12:04:48 GMT+0530 (IST)
Next log position: 6376
Event size: 56
Table id: 113
Schema: test
Table: testTable
Columns: 12
Column types: [ 3, 15, 3, 3, 15, 16, 15, 3, 3, 17, 3, 17 ]
app/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^
RangeError: index out of range
    at checkOffset (buffer.js:642:11)
    at Buffer.readInt32BE (buffer.js:807:5)
    at readIntBE (app/node_modules/zongji/lib/common.js:206:24)
    at Object.exports.readMysqlValue (app/node_modules/zongji/lib/common.js:522:21)
    at readRow (app/node_modules/zongji/lib/rows_event.js:113:16)
    at WriteRows.RowsEvent._fetchOneRow (app/node_modules/zongji/lib/rows_event.js:95:10)
    at WriteRows.RowsEvent (app/node_modules/zongji/lib/rows_event.js:64:27)
    at new WriteRows (app/node_modules/zongji/lib/rows_event.js:123:13)
    at BinlogHeader.parse (app/node_modules/zongji/lib/packet/binlog_header.js:47:23)
    at Protocol._parsePacket (app/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:262:12)

**Comment by java168** [comment]
i got exactly the same error as you when using Azure Database for MySQL server - PREVIEW (mine is wp_logs from wordpress)
i deleted the service and re-created a new one. the issue went away.  i don't know if the service had cached some tables information which i deleted that caused this issue. my local mysql server worked just ok.
