### ISSUE TITLE
Tests are not passed

### ISSUE THREAD

**Issue by nevill** [nevill/zongji#7]
When I try to run with `npm test`, it's failed

```
nevill@mba-nevill zongji(develop *) $ npm test

> zongji@0.2.0 test /Users/nevill/working/mysql-binlog/zongji
> nodeunit --reporter=minimal test

events:
/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'rows' of undefined
    at /Users/nevill/working/mysql-binlog/zongji/test/events.js:73:29
    at Query._callback (/Users/nevill/working/mysql-binlog/zongji/test/helpers/querySequence.js:22:11)
    at Query.Sequence.end (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.OkPacket (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:77:10)
    at Protocol._parsePacket (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

I also try to run them one by one. For example,
```
nevill@mba-nevill zongji(develop *) $ node_modules/.bin/nodeunit test/types.js

types.js
✖ set

AssertionError: 2 === 0
    at Object.strictEqual (/Users/nevill/working/mysql-binlog/zongji/node_modules/nodeunit/lib/types.js:83:39)
    at module.exports (/Users/nevill/working/mysql-binlog/zongji/test/helpers/expectEvents.js:10:8)
    at /Users/nevill/working/mysql-binlog/zongji/test/types.js:73:7
    at Query._callback (/Users/nevill/working/mysql-binlog/zongji/test/helpers/querySequence.js:22:11)
    at Query.Sequence.end (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/nevill/working/mysql-binlog/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
```

@numtel Is there anything missing? Or MySQL version matters? (I'm testing against 5.6.13)

**Comment by numtel** [comment]
Hmm I'm not sure what is happening. I have just updated from 5.5.40 to 5.6.19 and the tests all run fine still.

Do events dump correctly using example.js?

**Comment by numtel** [comment]
Ok, I have updated to 5.6.19 and I see the same error. (If you saw my [now] deleted message, I was still running the old 5.5.40 version, I had to actually restart my machine not just the MySQL server to switch versions). 

Please hold on, I'll see what's going on...

**Comment by numtel** [comment]
I just committed a fix for the first error you have posted but it only reveals the errors related to the different row format of MySQL 5.6. Now the error I receive is:

```
ben@x131e:~/mysql-binlog-tailer/zongji$ npm test

> zongji@0.2.0 test /home/ben/mysql-binlog-tailer/zongji
> nodeunit --reporter=minimal test

events: 
RangeError: Trying to access beyond buffer length
    at checkOffset (buffer.js:582:11)
    at Buffer.readUInt8 (buffer.js:588:5)
    at readRow (/home/ben/mysql-binlog-tailer/zongji/lib/rows_event.js:92:47)
    at WriteRows.RowsEvent._fetchOneRow (/home/ben/mysql-binlog-tailer/zongji/lib/rows_event.js:79:10)
    at WriteRows.RowsEvent (/home/ben/mysql-binlog-tailer/zongji/lib/rows_event.js:54:27)
    at new WriteRows (/home/ben/mysql-binlog-tailer/zongji/lib/rows_event.js:106:13)
    at BinlogHeader.parse (/home/ben/mysql-binlog-tailer/zongji/lib/packet/binlog_header.js:47:23)
    at Protocol._parsePacket (/home/ben/mysql-binlog-tailer/zongji/node_modules/mysql/lib/protocol/Protocol.js:253:12)
    at Parser.write (/home/ben/mysql-binlog-tailer/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at process._tickCallback (node.js:442:13)
```

Something has changed in the log format and the parser is reading past the end of the buffer. Will continue debugging tomorrow...

**Comment by numtel** [comment]
Also, I did try using the [`log_bin_use_v1_row_events` MySQL configuration option](http://dev.mysql.com/doc/refman/5.6/en/replication-options-binary-log.html#option_mysqld_log-bin-use-v1-row-events) but same same error persists.

**Comment by nevill** [comment]
@numtel Great, keep going! :+1:

**Comment by numtel** [comment]
Okay, the error about access beyond buffer length is directly related to the `binlog_checksum`.
Setting `binlog_checksum=NONE` makes many of the tests work.

I am working on a commit that makes it possible to have the checksum turned on (although it won't verify it being correct). The checksum is appended to the end of the row event but its length is not always 32 bits. Seems to be dependent on the number of columns but I'm still figuring that out.

It appears that there is also a different version of some field types in 5.6. So expect another commit regarding that.

**Comment by nevill** [comment]
Oh, it recalls me that, I intended to detect `checksum` by calling `show variables`, but for some reasons, I didn't finish that :smiling_imp:

**Comment by numtel** [comment]
No worries, skipping past the checksum is not too complicated. There's a [javascript implementation of the crc32 algorithm](https://github.com/SheetJS/js-crc32) but I'm not going to implement that right now.

This commit makes almost all of the tests pass now!

```
ben@x131e:~/mysql-binlog-tailer/zongji$ npm test

> zongji@0.2.0 test /home/ben/mysql-binlog-tailer/zongji
> nodeunit --reporter=minimal test

events: ...
filtering: ..
types: ..........Type Test Error:  temporal [ [Error: Unsupported type: undefined],
  { [Error: Packets out of order. Got: 196 Expected: 115] code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true } ]
FFF
AssertionError: 1 === 2
    at Object.strictEqual (/home/ben/mysql-binlog-tailer/zongji/node_modules/nodeunit/lib/types.js:83:39)
    at module.exports (/home/ben/mysql-binlog-tailer/zongji/test/helpers/expectEvents.js:10:8)
    at /home/ben/mysql-binlog-tailer/zongji/test/types.js:72:7
    at null._onTimeout (/home/ben/mysql-binlog-tailer/zongji/test/helpers/querySequence.js:23:13)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

AssertionError: 0 == 2
    at Object.equal (/home/ben/mysql-binlog-tailer/zongji/node_modules/nodeunit/lib/types.js:83:39)
    at /home/ben/mysql-binlog-tailer/zongji/test/types.js:81:12
    at null._onTimeout (/home/ben/mysql-binlog-tailer/zongji/test/helpers/querySequence.js:23:13)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

AssertionError: 2 === 0
    at Object.strictEqual (/home/ben/mysql-binlog-tailer/zongji/node_modules/nodeunit/lib/types.js:83:39)
    at module.exports (/home/ben/mysql-binlog-tailer/zongji/test/helpers/expectEvents.js:10:8)
    at /home/ben/mysql-binlog-tailer/zongji/test/types.js:72:7
    at null._onTimeout (/home/ben/mysql-binlog-tailer/zongji/test/helpers/querySequence.js:23:13)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

AssertionError: 2 === 0
    at Object.strictEqual (/home/ben/mysql-binlog-tailer/zongji/node_modules/nodeunit/lib/types.js:83:39)
    at module.exports (/home/ben/mysql-binlog-tailer/zongji/test/helpers/expectEvents.js:10:8)
    at /home/ben/mysql-binlog-tailer/zongji/test/types.js:72:7
    at null._onTimeout (/home/ben/mysql-binlog-tailer/zongji/test/helpers/querySequence.js:23:13)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)


FAILURES: 4/143 assertions failed (10719ms)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

Looks like something going on in one of the time data types. 

:sunglasses: Then onto testing other versions of MySQL I guess...

**Comment by numtel** [comment]
Got the `TIME2` data type decoded! :triumph: 
(Ignore the extra commits above, it's all the same one. I had some extra logging to remove and had to test multiple fraction precision levels)

Commands to run the new time tests:
```bash
$ node_modules/.bin/nodeunit --reporter=minimal test/types.js -t time_fraction
$ node_modules/.bin/nodeunit --reporter=minimal test/types.js -t time_no_fraction
```

`TIMESTAMP2` and `DATETIME2` should be pretty simple now but it's late so they have to wait... :sleeping:

**Comment by numtel** [comment]
@nevill With that last commit, you should have no problem using `npm test` to run all tests.
:smile:

**Comment by numtel** [comment]
@nevill Travis CI support will be ready soon, I will make it run the tests using all of the latest patch releases:
* 5.1.73
* 5.5.41
* 5.6.22
* 5.7.5 m15 (Might as well try...)

I just got it working with 5.1.73:
https://travis-ci.org/numtel/zongji/builds/47096255

Time to sleep now but the other versions will be very much the same. And, I have to make the tests actually quit on success. Right now, the process keeps running because ZongJi does not close its connection after the last test.

**Comment by nevill** [comment]
@numtel Awesome, wish you good luck on travis. :+1: 

But, the tests are still not passed on my MySQL 5.6.13.

```
nevill@mba-nevill zongji(master *) $ npm test

> zongji@0.2.0 test /Users/nevill/working/mysql-binlog/zongji
> nodeunit --reporter=minimal test

events:
/Users/nevill/working/mysql-binlog/zongji/test/events.js:75
          test.equal(events[1].rows[0].col, 10);
                              ^
TypeError: Cannot read property 'rows' of undefined
    at /Users/nevill/working/mysql-binlog/zongji/test/events.js:75:31
    at null._onTimeout (/Users/nevill/working/mysql-binlog/zongji/test/helpers/querySequence.js:23:13)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
npm ERR! Test failed.  See above for more details.
```

**Comment by numtel** [comment]
Check out these test results: https://travis-ci.org/nevill/zongji/builds/47205912
The badge is back on the readme :+1: 

The tests should probably now pass for you on your machine. I did run 5.6.13 on Travis successfully but for some reason Travis would not work with 4 MySQL servers running at the same time so I have limited the test to 5.1.73, 5.5.41, and 5.6.22 (newest patch versions of each minor release).

The output you posted about the undefined variable is due to the test looking for the events in ZongJi too soon after running the query in MySQL. Before this commit, the interval was 200ms. In order to make the tests run smoothly on Travis CI, the new default is 800ms.

If you still experience the same error, you may specify this delay using an environment variable when running the tests. Like this:

```bash
$ QUERY_DELAY=1200 npm test
```

**Comment by numtel** [comment]
@nevill With the commit I just posted, the delay has been replaced with simply waiting (up to 3000ms) for  the events to appear. You should no longer see that error at all and the tests run about 3x faster than before.

**Comment by nevill** [comment]
Finally, I see why I cannot have tests passed. It relates to `binlog_do_db = employees` I have set. :sob: 

Since there is [one gotcha](http://code.openark.org/blog/mysql/quick-reminder-avoid-using-binlog-do-db) on this option, I would remove it from `my.cnf`.
