### ISSUE TITLE
RangeError: Index out of range

### ISSUE THREAD

**Issue by chethanjkulkarni** [nevill/zongji#80]
RangeError: Index out of range
    at checkOffset (buffer.js:972:11)
    at Buffer.readUInt8 (buffer.js:1010:5)
    at readRow (C:\Users\Chethan\node_modules\zongji\lib\rows_event.js:109:47)
    at UpdateRows._fetchOneRow (C:\Users\Chethan\node_modules\zongji\lib\rows_event.js:146:12)
    at UpdateRows.RowsEvent (C:\Users\Chethan\node_modules\zongji\lib\rows_event.js:65:27)
    at new UpdateRows (C:\Users\Chethan\node_modules\zongji\lib\rows_event.js:137:13)
    at BinlogHeader.parse (C:\Users\Chethan\node_modules\zongji\lib\packet\binlog_header.js:47:23)
    at Protocol._parsePacket (C:\Users\Chethan\node_modules\zongji\node_modules\mysql\lib\protocol\Protocol.js:262:12)
    at Parser.write (C:\Users\Chethan\node_modules\zongji\node_modules\mysql\lib\protocol\Parser.js:74:12)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

**Comment by captainwillii** [comment]
I've also experienced this error this week.  The library appeared to be processing events which had occurred in the 'timezone' related tables in the mysql schema.  I wasn't interested in events in this schema so configured the listener to exclude it.  The error is no longer being thrown.
`
listener.start({
   includeEvents: ['writerows', 'tablemap', 'updaterows'],
   excludeSchema: { mysql: true }
});
`
 
I'm using MySql 5.7.20 in Docker (image mysql:5.7).

**Comment by rodrigogs** [comment]
Checkout my fork, I turned It into an error event instead of crashing the lib
