### ISSUE TITLE
parseNewDecimal is failing in Node 10.x

### ISSUE THREAD

**Issue by vlahupetar** [nevill/zongji#86]
There is an update to Buffer.writeInt8 which doesn't coerce the value into uint32.
Per the docs:
v10.0.0 | Removed noAssert and no implicit coercion of the offset to uint32 anymore.

This was probably failing in previous versions but silently v.s. explicitly now 

Switching to the UInt methods seems to have fixed the issue:
  var isPositive = (buffer.readUInt8(0) & (1 << 7)) === 128;
  buffer.writeUInt8(buffer.readUInt8(0) ^ (1 << 7), 0, true);

**Comment by nevill** [comment]
Well, I think it's safe to use `writeInt8` + `readInt8` here. I tested (even with `noAssert=true` parameter) against node v10.6.0, didn't see any errors. Or, can you show me some error scenario by playing with [testing code here](https://github.com/nevill/zongji/blob/a519af7a9b770d475b8afa578664732689c64bfb/test/types.js#L220) ?

**Comment by vlahupetar** [comment]
@nevill,
the standard tests fail on node 10; did you remember to update docker-test.sh to use node:10 for running the tests?

following is the test results:
`
% ./docker-test.sh                                                                                                                                                                                                  18-07-08 - 11:40:17
mysql55

> zongji@0.4.5 test /build
> nodeunit --reporter=minimal test

errors: (node:17) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
.....
events: .(node:17) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
....
filtering: ...
types: .......Type Test Error:  decimal [ RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received -256
      at writeU_Int8 (internal/buffer.js:561:11)
      at Buffer.writeInt8 (internal/buffer.js:692:10)
      at parseNewDecimal (/build/lib/common.js:240:10)
      at Object.exports.readMysqlValue (/build/lib/common.js:445:16)
      at readRow (/build/lib/rows_event.js:111:16)
      at WriteRows.RowsEvent._fetchOneRow (/build/lib/rows_event.js:93:10)
      at WriteRows.RowsEvent (/build/lib/rows_event.js:62:27)
      at new WriteRows (/build/lib/rows_event.js:121:13)
      at BinlogHeader.parse (/build/lib/packet/binlog_header.js:47:23)
      at Protocol._parsePacket (/build/node_modules/mysql/lib/protocol/Protocol.js:261:12)
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at process._tickCallback (internal/process/next_tick.js:61:11),
  RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received 255
      at writeU_Int8 (internal/buffer.js:561:11)
      at Buffer.writeInt8 (internal/buffer.js:692:10)
      at parseNewDecimal (/build/lib/common.js:240:10)
      at Object.exports.readMysqlValue (/build/lib/common.js:445:16)
      at readRow (/build/lib/rows_event.js:111:16)
      at WriteRows.RowsEvent._fetchOneRow (/build/lib/rows_event.js:93:10)
      at WriteRows.RowsEvent (/build/lib/rows_event.js:62:27)
      at new WriteRows (/build/lib/rows_event.js:121:13)
      at BinlogHeader.parse (/build/lib/packet/binlog_header.js:47:23)
      at Protocol._parsePacket (/build/node_modules/mysql/lib/protocol/Protocol.js:261:12)
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/build/node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/build/node_modules/mysql/lib/Connection.js:103:28)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11),
  RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received -256
      at writeU_Int8 (internal/buffer.js:561:11)
      at Buffer.writeInt8 (internal/buffer.js:692:10)
      at parseNewDecimal (/build/lib/common.js:240:10)
      at Object.exports.readMysqlValue (/build/lib/common.js:445:16)
      at readRow (/build/lib/rows_event.js:111:16)
      at WriteRows.RowsEvent._fetchOneRow (/build/lib/rows_event.js:93:10)
      at WriteRows.RowsEvent (/build/lib/rows_event.js:62:27)
      at new WriteRows (/build/lib/rows_event.js:121:13)
      at BinlogHeader.parse (/build/lib/packet/binlog_header.js:47:23)
      at Protocol._parsePacket (/build/node_modules/mysql/lib/protocol/Protocol.js:261:12)
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/build/node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/build/node_modules/mysql/lib/Connection.js:103:28)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11),
  RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received 255
      at writeU_Int8 (internal/buffer.js:561:11)
      at Buffer.writeInt8 (internal/buffer.js:692:10)
      at parseNewDecimal (/build/lib/common.js:240:10)
      at Object.exports.readMysqlValue (/build/lib/common.js:445:16)
      at readRow (/build/lib/rows_event.js:111:16)
      at WriteRows.RowsEvent._fetchOneRow (/build/lib/rows_event.js:93:10)
      at WriteRows.RowsEvent (/build/lib/rows_event.js:62:27)
      at new WriteRows (/build/lib/rows_event.js:121:13)
      at BinlogHeader.parse (/build/lib/packet/binlog_header.js:47:23)
      at Protocol._parsePacket (/build/node_modules/mysql/lib/protocol/Protocol.js:261:12)
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/build/node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/build/node_modules/mysql/lib/Connection.js:103:28)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11),
  RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received -256
      at writeU_Int8 (internal/buffer.js:561:11)
      at Buffer.writeInt8 (internal/buffer.js:692:10)
      at parseNewDecimal (/build/lib/common.js:240:10)
      at Object.exports.readMysqlValue (/build/lib/common.js:445:16)
      at readRow (/build/lib/rows_event.js:111:16)
      at WriteRows.RowsEvent._fetchOneRow (/build/lib/rows_event.js:93:10)
      at WriteRows.RowsEvent (/build/lib/rows_event.js:62:27)
      at new WriteRows (/build/lib/rows_event.js:121:13)
      at BinlogHeader.parse (/build/lib/packet/binlog_header.js:47:23)
      at Protocol._parsePacket (/build/node_modules/mysql/lib/protocol/Protocol.js:261:12)
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/build/node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/build/node_modules/mysql/lib/Connection.js:103:28)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11),
  RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received 255
      at writeU_Int8 (internal/buffer.js:561:11)
      at Buffer.writeInt8 (internal/buffer.js:692:10)
      at parseNewDecimal (/build/lib/common.js:240:10)
      at Object.exports.readMysqlValue (/build/lib/common.js:445:16)
      at readRow (/build/lib/rows_event.js:111:16)
      at WriteRows.RowsEvent._fetchOneRow (/build/lib/rows_event.js:93:10)
      at WriteRows.RowsEvent (/build/lib/rows_event.js:62:27)
      at new WriteRows (/build/lib/rows_event.js:121:13)
      at BinlogHeader.parse (/build/lib/packet/binlog_header.js:47:23)
      at Protocol._parsePacket (/build/node_modules/mysql/lib/protocol/Protocol.js:261:12)
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/build/node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/build/node_modules/mysql/lib/Connection.js:103:28)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11),
  RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received -256
      at writeU_Int8 (internal/buffer.js:561:11)
      at Buffer.writeInt8 (internal/buffer.js:692:10)
      at parseNewDecimal (/build/lib/common.js:240:10)
      at Object.exports.readMysqlValue (/build/lib/common.js:445:16)
      at readRow (/build/lib/rows_event.js:111:16)
      at WriteRows.RowsEvent._fetchOneRow (/build/lib/rows_event.js:93:10)
      at WriteRows.RowsEvent (/build/lib/rows_event.js:62:27)
      at new WriteRows (/build/lib/rows_event.js:121:13)
      at BinlogHeader.parse (/build/lib/packet/binlog_header.js:47:23)
      at Protocol._parsePacket (/build/node_modules/mysql/lib/protocol/Protocol.js:261:12)
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/build/node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/build/node_modules/mysql/lib/Connection.js:103:28)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11),
  RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received -256
      at writeU_Int8 (internal/buffer.js:561:11)
      at Buffer.writeInt8 (internal/buffer.js:692:10)
      at parseNewDecimal (/build/lib/common.js:240:10)
      at Object.exports.readMysqlValue (/build/lib/common.js:445:16)
      at readRow (/build/lib/rows_event.js:111:16)
      at WriteRows.RowsEvent._fetchOneRow (/build/lib/rows_event.js:93:10)
      at WriteRows.RowsEvent (/build/lib/rows_event.js:62:27)
      at new WriteRows (/build/lib/rows_event.js:121:13)
      at BinlogHeader.parse (/build/lib/packet/binlog_header.js:47:23)
      at Protocol._parsePacket (/build/node_modules/mysql/lib/protocol/Protocol.js:261:12)
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/build/node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/build/node_modules/mysql/lib/Connection.js:103:28)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11),
  RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received -256
      at writeU_Int8 (internal/buffer.js:561:11)
      at Buffer.writeInt8 (internal/buffer.js:692:10)
      at parseNewDecimal (/build/lib/common.js:240:10)
      at Object.exports.readMysqlValue (/build/lib/common.js:445:16)
      at readRow (/build/lib/rows_event.js:111:16)
      at WriteRows.RowsEvent._fetchOneRow (/build/lib/rows_event.js:93:10)
      at WriteRows.RowsEvent (/build/lib/rows_event.js:62:27)
      at new WriteRows (/build/lib/rows_event.js:121:13)
      at BinlogHeader.parse (/build/lib/packet/binlog_header.js:47:23)
      at Protocol._parsePacket (/build/node_modules/mysql/lib/protocol/Protocol.js:261:12)
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/build/node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/build/node_modules/mysql/lib/Connection.js:103:28)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11) ]

FAILURES: Undone tests (or their setups/teardowns): 
- decimal

To fix this, make sure all tests call test.done()
npm ERR! Test failed.  See above for more details.
mysql56

> zongji@0.4.5 test /build
> nodeunit --reporter=minimal test

errors: (node:17) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
.....
events: .(node:17) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
....
filtering: ...
types: .......Type Test Error:  decimal [ RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received -256
      at writeU_Int8 (internal/buffer.js:561:11)
      at Buffer.writeInt8 (internal/buffer.js:692:10)
      at parseNewDecimal (/build/lib/common.js:240:10)
      at Object.exports.readMysqlValue (/build/lib/common.js:445:16)
      at readRow (/build/lib/rows_event.js:111:16)
      at WriteRows.RowsEvent._fetchOneRow (/build/lib/rows_event.js:93:10)
      at WriteRows.RowsEvent (/build/lib/rows_event.js:62:27)
      at new WriteRows (/build/lib/rows_event.js:121:13)
      at BinlogHeader.parse (/build/lib/packet/binlog_header.js:47:23)
      at Protocol._parsePacket (/build/node_modules/mysql/lib/protocol/Protocol.js:261:12)
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at process._tickCallback (internal/process/next_tick.js:61:11),
  { Error: Packets out of order. Got: 164 Expected: 29
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:42:19)
      at process._tickCallback (internal/process/next_tick.js:61:11)
      --------------------
      at Protocol._enqueue (/build/node_modules/mysql/lib/protocol/Protocol.js:145:48)
      at Immediate._start (/build/index.js:235:31)
      at runCallback (timers.js:696:18)
      at tryOnImmediate (timers.js:667:5)
      at processImmediate (timers.js:649:5) code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true } ]

FAILURES: Undone tests (or their setups/teardowns): 
- decimal

To fix this, make sure all tests call test.done()
npm ERR! Test failed.  See above for more details.
mysql57

> zongji@0.4.5 test /build
> nodeunit --reporter=minimal test

errors: (node:16) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
.....
events: .(node:16) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
....
filtering: ...
types: .......Type Test Error:  decimal [ RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -128 and <= 127. Received -256
      at writeU_Int8 (internal/buffer.js:561:11)
      at Buffer.writeInt8 (internal/buffer.js:692:10)
      at parseNewDecimal (/build/lib/common.js:240:10)
      at Object.exports.readMysqlValue (/build/lib/common.js:445:16)
      at readRow (/build/lib/rows_event.js:111:16)
      at WriteRows.RowsEvent._fetchOneRow (/build/lib/rows_event.js:93:10)
      at WriteRows.RowsEvent (/build/lib/rows_event.js:62:27)
      at new WriteRows (/build/lib/rows_event.js:121:13)
      at BinlogHeader.parse (/build/lib/packet/binlog_header.js:47:23)
      at Protocol._parsePacket (/build/node_modules/mysql/lib/protocol/Protocol.js:261:12)
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at process._tickCallback (internal/process/next_tick.js:61:11),
  { Error: Packets out of order. Got: 148 Expected: 125
      at Parser.write (/build/node_modules/mysql/lib/protocol/Parser.js:42:19)
      at process._tickCallback (internal/process/next_tick.js:61:11)
      --------------------
      at Protocol._enqueue (/build/node_modules/mysql/lib/protocol/Protocol.js:145:48)
      at Immediate._start (/build/index.js:235:31)
      at runCallback (timers.js:696:18)
      at tryOnImmediate (timers.js:667:5)
      at processImmediate (timers.js:649:5) code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true } ]

FAILURES: Undone tests (or their setups/teardowns): 
- decimal

To fix this, make sure all tests call test.done()
npm ERR! Test failed.  See above for more details.

`

**Comment by nevill** [comment]
Oh, my mistake, I can see the errors now. Just played with a local copy of node instead of the one within docker images. 😅

**Comment by vlahupetar** [comment]
Hi @nevill,
Whats going on with the merge request? Is there anything you need from me to accept the merge request?
Thanks

**Comment by nevill** [comment]
I was trying to understand what node.js core team did to those Buffer.write* methods.
Thanks for the PR anyway, it's merged.

**Comment by vlahupetar** [comment]
@nevill, are you going to make a release with this change soon?
